Refactor: Change migration contract
truflation/truflation-contracts pull request #42
Opened 2024-05-09 11:52 UTC by Dev-Doggo

2024-05-09 11:58 UTC, Dev-Doggo commented
I was under the impression these changes were already merged as they should've been included with the audit.
I don't think doing an audit on this is necessary as the contract is extremely simple and I've worked with this code in the past.
cc: @markholdex @zolotokrylin

2024-05-09 12:06 UTC, Dev-Doggo commented
I was under the impression these changes were already merged as they should've been included with the audit.
I don't think doing an audit on this is necessary as the contract is extremely simple and I've worked with this code in the past.

Note: I've force pushed this branch to a new commit off main so the commit name follows our guidelines.
cc: @markholdex @zolotokrylin

2024-05-10 13:34 UTC, markholdex requested changes
@Dev-Doggo PR is not linked with to a Problem issue

2024-05-13 12:58 UTC, lewis999bits requested changes
@Dev-Doggo All good. see my comments

2024-05-13 12:58 UTC, lewis999bits commented on src/token/TrufMigrator.sol
> +    function _recoverSigner(address user, uint256 maxMigrationAmount, uint8 v, bytes32 r, bytes32 s) internal pure returns(address) {
If we switch to ECDSA, we'd need `verify` function for checking the user is valid for migration. 
Perhaps return the boolean value for verification result instead of signer address and just make this function `public` would be good solution. What do you think?

2024-05-13 14:41 UTC, markholdex requested changes
@Dev-Doggo I understand the PR doesn't have a problem. It's also ok. However ,can you specify:

- What problem we are solving with this PR in the description at least? 
- Is is something that we actually need now? Why? 
- How will it impact the audit? It seems like we need to re-request on these changes too. But I'm not sure if they will be accepted.

2024-05-13 15:38 UTC, Dev-Doggo commented
> * What problem we are solving with this PR in the description at least?

I had discussed the advantages and disadvantages of using ECDSA instead of Merke Proofs with Cameron a while back and decided to go with this approach. No "problem" existed, it was just a better approach

> * Is is something that we actually need now? Why?

See above

> * How will it impact the audit? It seems like we need to re-request on these changes too. But I'm not sure if they will be accepted.

I don't think an audit is necessary here, I've used this code in the past as well, I have a lot of experience with using ECDSA signatures for verification purposes

2024-05-13 18:16 UTC, lewis999bits approved these changes

2024-05-13 18:58 UTC, markholdex approved these changes

2024-05-13 18:59 UTC, markholdex commented
@Dev-Doggo I have updated the description with the benefits of this upgrade on what I found on the internet and that are relevant to our use case. You can add/update with more that you are aware of. 

p.s. I noticed you linked with the Problem too.

2024-05-13 18:59 UTC, merged