fix: add additional event
truflation/truflation-contracts pull request #51
Opened 2024-05-10 13:21 UTC by Dev-Doggo

Closes: truflation/truf-claim-page#229

The previous values change has not been implemented, I don't see a reason for it.

cc: @markholdex @zolotokrylin

2024-05-10 18:58 UTC, lewis999bits requested changes

2024-05-10 18:58 UTC, lewis999bits commented on src/staking/StakingRewards.sol
> +		emit RewardsDistributionUpdated(_rewardsDistribution);
@Dev-Doggo Please keep an eye on the style

2024-05-10 19:38 UTC, Dev-Doggo commented on src/staking/StakingRewards.sol
> +		emit RewardsDistributionUpdated(_rewardsDistribution);
Fixed, can we please get #39 merged, fighting prettier constantly is annoying

cc: @markholdex @zolotokrylin

2024-05-13 11:58 UTC, lewis999bits approved these changes

2024-05-13 11:59 UTC, merged