feat: sanity checks
truflation/truflation-contracts pull request #58
Opened 2024-05-13 17:10 UTC by Dev-Doggo

Closes: truflation/truf-claim-page#224

2024-05-13 17:14 UTC, Dev-Doggo commented
@markholdex I really don't like how this code looks imo, but if it's something we want to implement, sure 🤷‍♂️ 

cc: @zolotokrylin

2024-05-13 19:47 UTC, lewis999bits submitted a review, later dismissed

2024-05-13 20:08 UTC, lewis999bits requested changes

2024-05-13 20:08 UTC, lewis999bits commented on src/staking/StakingRewards.sol
> +        require(IERC20(_rewardsToken).totalSupply() > 0, "Invalid token");
@Dev-Doggo Please add sanity check for zero addresses as you did in `VirtualStakingRewards`

2024-05-14 03:21 UTC, zolotokrylin commented on src/TrufPartner.sol
> +        }
You don't need this. A vesting contract is not supposed to check if the supply of the token is the correct supply. The token you pass in the constructor already has the correct supply.

What the auditor meant, as I understand, is that you check the token supply when you call a function, where you supply the token amount to be used. So when you have for example ABC token with a total supply of 100 tokens, you must not allow the vesting admin to set 1,000 tokens for vesting.

Or am I missing something?

2024-05-14 11:18 UTC, Dev-Doggo commented on src/TrufPartner.sol
> +        }
@zolotokrylin If you check the references the auditor left they all link to the constructor arguments, this is what I understood from it even though as I said previously I've never seen this implemented in any other protocol.
I still think this is completely unnecessary to implement

Also I think implementing what you suggested for the vesting contract is going to be quite costly in terms of user gas, I'd need to look into it further if we actually want to implement that, please let me know!

2024-05-15 14:02 UTC, lewis999bits commented
@Dev-Doggo I just reviewed the code and for me I cannot approve or reject this PR.
I've never seen this kind of check before and those lines cannot cover the sanity check 100%.
Is this what audit team really want to do? 
cc @markholdex @zolotokrylin

2024-05-15 14:06 UTC, Dev-Doggo commented
> @Dev-Doggo I just reviewed the code and for me I cannot approve or reject this PR. I've never seen this kind of check before and those lines cannot cover the sanity check 100%. Is this what audit team really want to do?

@lewis999bits As far as I understand it yes, the point is that if the address passed in is incorrect the `.totalSupply`/`.balanceOf` calls will fail as it will not return any data/revert.

I don't think it's necessary to implement this though, it was quick to do so which is why I implemented it and we can discuss if it's something we want to merge.

2024-05-15 14:25 UTC, lewis999bits approved these changes

2024-05-15 14:55 UTC, lewis999bits commented
@Dev-Doggo I don't know if I'm out of this context, but the sanity check the audit team supposed is more likely needed for the dynamic contract deployment (f.e factory contract). Our smart contracts are one-click deployment and the checks can be done whether manually or via script. This PR just increase unnecessary codes and increase deployment gas fee which is painful for us. And in terms of architecture, it makes our code poor.

2024-05-15 14:58 UTC, Dev-Doggo commented
> @Dev-Doggo I don't know if I'm out of this context, but the sanity check the audit team supposed is more likely needed for the dynamic contract deployment (f.e factory contract). Our smart contracts are one-click deployment and the checks can be done whether manually or via script. This PR just increase unnecessary codes and increase deployment gas fee which is painful for us. And in terms of architecture, it makes our code poor.

I agree with you, some of those points I also raised with the auditor in the initial Problem as well, they said they can remove this from the final report even with no fixes.

cc @zolotokrylin

2024-05-15 15:02 UTC, markholdex commented
@Dev-Doggo @lewis999bits alright. Let's close without merging.

2024-05-15 15:02 UTC, closed without merging

2024-05-15 15:02 UTC, markholdex commented
Don't delete the branch yet